[custom]
;ACL4SSR_Online_Full.ini基础修改
;2025.12.05更新

;去广告：支持，已关闭
;自动测速：支持
;增强中国IP段：支持
;增强国外GFW：支持

;单独规则
ruleset=🎮 游戏平台,[]DOMAIN-SUFFIX,steamusercontent.com
;规则集定义
ruleset=🚀 默认节点,https://raw.githubusercontent.com/whm188400131/VPN/main/Clash/Proxylist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/whm188400131/VPN/main/Clash/Directlist.list
ruleset=🚀 默认节点,https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/whm188400131/VPN/refs/heads/main/Clash/appleAI.list
ruleset=🌍 Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=🤖 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🤖 Gemini,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🖥 TeamViewer,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TeamViewer/TeamViewer.list
ruleset=📺 Plex,https://raw.githubusercontent.com/whm188400131/VPN/main/Clash/Plex.list
ruleset=📺 v4.Plex,https://raw.githubusercontent.com/whm188400131/VPN/main/Clash/v4Plex.list
ruleset=🗄 Synology,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Synology/Synology.list
ruleset=🎨 Adobe,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Adobe/Adobe.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
;ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🎮 Blizzard,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=🌍 Reddit,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📸 Instagram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.list
ruleset=💬 微信,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=📺 BiliBili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 BiliBili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=📺 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 默认节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 默认节点,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 兜底策略,[]FINAL
;规则集定义

;策略组定义
custom_proxy_group=🚀 默认节点`select`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]♻️ 自动选择`[]🌐 手动选择`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🌍 Reddit`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🎮 游戏平台`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🎮 Blizzard`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=📹 YouTube`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🎵 TikTok`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=📸 Instagram`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=📲 Telegram`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🎥 Netflix`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
custom_proxy_group=🎨 Adobe`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🤖 OpenAI`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
custom_proxy_group=🤖 Copilot`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
custom_proxy_group=🤖 Gemini`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=🌍 Bing`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=🪟 Microsoft`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=🖥 TeamViewer`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=📺 Plex`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT 
custom_proxy_group=📺 v4.Plex`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=🗄 Synology`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=💬 微信`select`[]DIRECT
custom_proxy_group=📺 BiliBili`select`[]DIRECT`[]🇭🇰 香港`[]🇨🇳 台湾
custom_proxy_group=📺 国外媒体`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
custom_proxy_group=📺 国内媒体`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国
custom_proxy_group=🎯 全球直连`select`[]DIRECT
;custom_proxy_group=📢 谷歌FCM`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
;custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 默认节点`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
;custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 兜底策略`select`[]🌐 手动选择`[]♻️ 自动选择`[]🇺🇲 美国`[]🇭🇰 香港`[]🇯🇵 日本`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇬🇧 英国`[]DIRECT
custom_proxy_group=🌐 手动选择`select`.*
;策略组定义

;节点定义
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,,20
#custom_proxy_group=🇺🇲 美国`fallback`[]🇺🇲 BGP美国`[]🇺🇲 nonBGP美国`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇺🇲 美国`url-test`(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇭🇰 香港`url-test`(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇯🇵 日本`url-test`(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇨🇳 台湾`url-test`(?=.*(台|新北|彰化|TW|Taiwan))^((?!(港|日|韩|新|美)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇸🇬 新加坡`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇰🇷 韩国`url-test`(?=.*(KR|Korea|KOR|首尔|韩|韓))^((?!(港|台|新|日|美)).)*$`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇬🇧 英国`url-test`(?=.*(英|UK))`http://www.gstatic.com/generate_204`600,,20
;节点定义

enable_rule_generator=true
overwrite_original_rules=true
